"use client";

import { useEffect, useMemo, useState } from 'react';
import dynamic from 'next/dynamic';
import { AlertTriangle, CalendarClock, ExternalLink, Loader2, MapPin, RefreshCw, ShieldAlert, Skull, Users } from 'lucide-react';
import type { CuratedConflictEntry, WikipediaConflict, WikipediaConflictsData } from '@/lib/types';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

const MapDisplay = dynamic(() => import('./map-display'), { ssr: false, loading: () => <div className="h-[560px] rounded-lg bg-muted/30 flex items-center justify-center text-muted-foreground">Carregando mapa...</div> });
const SOURCE_URL = 'https://en.wikipedia.org/wiki/List_of_ongoing_armed_conflicts';

function severityLabel(value: WikipediaConflict['severity']) { return value === 'HIGH' ? 'Alta' : value === 'MEDIUM' ? 'Média' : value === 'LOW' ? 'Baixa' : 'Não classificada'; }
function severityClass(value: WikipediaConflict['severity']) { return value === 'HIGH' ? 'border-red-200 bg-red-50 text-red-800' : value === 'MEDIUM' ? 'border-orange-200 bg-orange-50 text-orange-800' : value === 'LOW' ? 'border-yellow-200 bg-yellow-50 text-yellow-800' : 'border-slate-200 bg-slate-50 text-slate-700'; }
function toMapConflict(c: WikipediaConflict): CuratedConflictEntry | null {
  if (typeof c.latitude !== 'number' || typeof c.longitude !== 'number') return null;
  const severityCategory = c.severity === 'HIGH' ? 'Alta Gravidade' : c.severity === 'MEDIUM' ? 'Média Gravidade' : c.severity === 'LOW' ? 'Baixa Gravidade' : undefined;
  return { nome: c.name, imagem_url: '', inicio: c.startDate || '', fatalidades_texto: c.fatalitiesRaw, territorio: c.territory || '', coordenadas: [c.latitude, c.longitude], envolvidos: c.locations, wikipedia_link: c.detailsLink || SOURCE_URL, status: 'Ativo', tipo_conflito: 'Conflito armado', data_ultima_atualizacao_fatalidades: 'Conforme a fonte original', impacto_humanitario: '', atores_externos_envolvidos: '', tendencia_recente: '', fonte_dados_especifica: SOURCE_URL, regiao_geopolitica: '', severityCategory };
}

export function WikipediaMacroPanel() {
  const [data, setData] = useState<WikipediaConflictsData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const load = async (refresh = false) => { setLoading(true); setError(null); try { const response = await fetch(`/api/conflicts${refresh ? '?refresh=1' : ''}`, { cache: 'no-store' }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'Falha ao atualizar conflitos.'); setData(payload); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Falha ao atualizar conflitos.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const mapped = useMemo(() => (data?.conflicts || []).map(toMapConflict).filter((x): x is CuratedConflictEntry => x !== null), [data]);
  if (loading) return <div className="min-h-[560px] flex flex-col items-center justify-center gap-3 text-muted-foreground"><Loader2 className="h-8 w-8 animate-spin text-primary" /><p>Consultando a fonte atual de conflitos...</p></div>;
  if (error || !data) return <div className="min-h-[300px] flex flex-col items-center justify-center gap-4 rounded-lg border border-red-200 bg-red-50 p-6 text-center"><AlertTriangle className="h-8 w-8 text-red-600" /><p className="max-w-xl text-red-800">{error || 'Nenhum dado atual disponível.'}</p><Button onClick={() => void load()} variant="outline"><RefreshCw className="mr-2 h-4 w-4" />Tentar novamente</Button></div>;
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xl font-semibold">Conflitos armados em andamento</h3><p className="text-sm text-muted-foreground">Dados extraídos da fonte original e armazenados temporariamente no Turso.</p></div><Button onClick={() => void load(true)} variant="outline" size="sm"><RefreshCw className="mr-2 h-4 w-4" />Atualizar fonte</Button></div><div className="flex items-center justify-between rounded-md border bg-muted/30 px-3 py-2 text-xs text-muted-foreground"><span className="flex items-center gap-1"><CalendarClock className="h-3.5 w-3.5" />Processado em {new Date(data.lastUpdated).toLocaleString('pt-BR')}</span><a className="flex items-center gap-1 underline" href={SOURCE_URL} target="_blank" rel="noreferrer">Fonte <ExternalLink className="h-3 w-3" /></a></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-lg border p-4"><ShieldAlert className="mb-2 h-5 w-5 text-primary" /><strong className="block text-2xl">{data.conflicts.length}</strong><span className="text-xs text-muted-foreground">Conflitos retornados pela fonte</span></div><div className="rounded-lg border p-4"><MapPin className="mb-2 h-5 w-5 text-primary" /><strong className="block text-2xl">{mapped.length}</strong><span className="text-xs text-muted-foreground">Com coordenadas geocodificadas</span></div><div className="rounded-lg border p-4"><Skull className="mb-2 h-5 w-5 text-primary" /><strong className="block text-2xl">Não agregado</strong><span className="text-xs text-muted-foreground">Fatalidades não são somadas</span></div></div><MapDisplay conflicts={mapped} /><div className="grid gap-4 md:grid-cols-2">{data.conflicts.map(c => <article className="rounded-lg border bg-card p-4" key={c.id}><div className="mb-2 flex items-start justify-between gap-2"><h4 className="font-semibold">{c.name}</h4><Badge className={severityClass(c.severity)}>{severityLabel(c.severity)}</Badge></div><p className="mb-2 flex gap-2 text-sm text-muted-foreground"><Skull className="h-4 w-4 shrink-0" />{c.fatalitiesRaw}</p><p className="mb-2 flex gap-2 text-sm text-muted-foreground"><Users className="h-4 w-4 shrink-0" />{c.locations.join(', ') || 'Localização não informada'}</p>{c.startDate && <p className="text-xs text-muted-foreground">Início: {c.startDate}</p>}{c.detailsLink && <a className="mt-3 inline-flex items-center gap-1 text-xs text-primary underline" href={c.detailsLink} target="_blank" rel="noreferrer">Ver detalhes <ExternalLink className="h-3 w-3" /></a>}</article>)}</div></div>;
}
